In [1]:
from sklearn import linear_model
import numpy as np

In [4]:
lin_reg_gas = linear_model.LinearRegression(positive=True)
lin_reg_water = linear_model.LinearRegression(positive=True)
lin_reg_electricity = linear_model.LinearRegression(positive=True)

In [3]:
# From March 2021 to Nov 2022
x_gas = np.array([70, 48, 10, 13, 13, 9, 8, 20, 107, 174, 230, 174, 165, 83, 4, 5, 4, 5, 16, 16, 71, 125, 137, 115, 84, 54])
y_gas = [8110, 5857, 1981, 2294, 2291, 1887, 1783, 3007, 11847, 18626, 24417, 18829, 17933, 9022, 1325, 1572, 1295, 1486, 1972, 3268, 8259, 13709, 14956, 12743, 8654, 6434]

# From March 2021 to Oct 2022
x_water = np.array([7, 7, 6, 8, 8, 8, 8, 5, 6, 7, 5, 5, 6, 4, 3, 3, 2, 8, 6, 8, 10, 4, 9, 10])
y_water = [4371, 4371, 3746, 4995, 5302, 4639, 5010, 4071, 3757, 4384, 3170, 3170, 3804, 2536, 1969, 1969, 1268, 5072, 3669, 5072, 6225, 2613, 10190, 11322]

#From March 2021 to Nov 2022
x_electricity = np.array([235, 207, 172, 149, 157, 175, 182, 121, 419, 683, 504, 342, 304, 162, 115, 101, 82, 131, 112, 78, 124, 54, 112, 152, 105, 82])
y_electricity = [8830, 7770, 6462, 5607, 5904, 4775, 6966, 4572, 15734, 25521, 19047, 12852, 11417, 6087, 4319, 3818, 3123, 4897, 4209, 2978, 10950, 2445, 1821, 5658, 3956, 3123]

In [9]:
# Gas
lin_reg_gas.fit(x_gas.reshape(-1, 1), y_gas)
lin_reg_gas.predict(np.array([125]).reshape(-1, 1))
# lin_reg_gas.score(x_gas.reshape(-1, 1), y_gas)

array([13708.9600991])

In [11]:
# Water
lin_reg_water.fit(x_water.reshape(-1, 1), y_water)
lin_reg_water.predict(np.array([4]).reshape(-1, 1))
# lin_reg_water.score(x_water.reshape(-1, 1), y_water)

array([2613.22058824])

In [12]:
# Electricity
lin_reg_electricity.fit(x_electricity.reshape(-1, 1), y_electricity)
lin_reg_electricity.predict(np.array([54]).reshape(-1, 1))
# lin_reg_electricity.score(x_electricity.reshape(-1, 1), y_electricity)

array([2445.23994857])